language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
services:
  - redis-server
  - mongo-server
addons:
  hosts:
    - redis
    - mongo
before_install:
  - npm install --global yarn
install:
  - make
